
stages:
  get_data:
      cmd: zsh src/get_data.zsh
      deps:
        - src/get_data.zsh
        - Dockerfile
      outs:
        - profiling/profiling_data/LFQ_timsTOFPro_diaPASEF_Ecoli_01.d
        - profiling_data/UP000000625_83333_crap.fasta
        - profiling_data/UP000005640_9606_crap.fasta

  orbi_run:
    deps:
      - src/run.py
      - config/orbi.toml
    cmd: python src/run.py --

  tims_run:
      - src/run.py
      - config/tims.toml

plots:
  - orbi_qvals.csv:
      y: [n_peptides]
      x: q_val
  - orbi_td.png
  - tims_qvals.csv:
      y: [n_peptides]
      x: q_val
  - tims_td.png
